from pathlib import Path
from datetime import datetime


OUTPUT_FOLDER = Path("outputs")
OUTPUT_FOLDER.mkdir(exist_ok=True)


def save_output(file_prefix, content):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    file_name = f"{file_prefix}_{timestamp}.txt"
    file_path = OUTPUT_FOLDER / file_name

    file_path.write_text(content, encoding="utf-8")

    return file_path


def create_email(receiver, subject, body):
    content = f"""
========================================
EMAIL DRAFT
========================================

To: {receiver}
Subject: {subject}

{body}
"""

    file_path = save_output("email", content)

    return f"""
{content}

Saved successfully:
{file_path}
"""


def create_report(title, report_content):
    content = f"""
========================================
BUSINESS REPORT
========================================

Title: {title}

{report_content}
"""

    file_path = save_output("report", content)

    return f"""
{content}

Saved successfully:
{file_path}
"""


def create_support_response(customer_name, issue, response):
    content = f"""
========================================
CUSTOMER SUPPORT RESPONSE
========================================

Customer:
{customer_name}

Issue:
{issue}

Response:
{response}

---
Generated by:
AI Business Automation Agent
"""

    file_path = save_output("support_response", content)

    return f"""
{content}

Saved successfully:
{file_path}
"""